<?php
require_once('body.php');
require_once('car_body.php');
require_once('van_body.php');
require_once('chassis.php');
require_once('car_chassis.php');
require_once('van_chassis.php');
require_once('windows.php');
require_once('car_windows.php');
require_once('van_windows.php');
require_once('abstract_vehicle_factory.php');
require_once('car_factory.php');
require_once('van_factory.php');
?> 
