<?php
require_once('../chapter01/engine.php');
require_once('../chapter01/abstract_engine.php');
require_once('../chapter01/standard_engine.php');
require_once('../chapter01/turbo_engine.php');
require_once('vehicle.php');
require_once('abstract_vehicle.php');
require_once('../chapter01/abstract_car.php');
require_once('../chapter01/abstract_van.php');
require_once('saloon.php');
require_once('coupe.php');
require_once('sport.php');
require_once('boxvan.php');
require_once('pickup.php');

require_once('abstract_vehicle_option.php');
require_once('air_conditioned_vehicle.php');
require_once('alloy_wheeled_vehicle.php');
require_once('leather_seated_vehicle.php');
require_once('metallic_painted_vehicle.php');
require_once('sat_nav_vehicle.php');
?> 
